// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcjokqkuwbpjjjinpnjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhjam9rcWt1d2JwampqaW5wbmp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MDUyNjQsImV4cCI6MjA2ODk4MTI2NH0.NzBGXs6dMHYCS1A06Pm9J2_MTJF1SaHi51-OzBEiqUY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});